package com.example.positionfinder.service;

import java.util.HashMap;
import java.util.Map;

public class TestMap {
    public static Map<String, String> createMap() {
        Map<String, String> jobTitles = new HashMap<>();

        // Add the job titles as keys with "1" values
        jobTitles.put("Operation Coordinator- 50073625", "1");
        jobTitles.put("Operation Coordinator- 50073625 with verification", "1");
        jobTitles.put("Compensation & Benefits Analyst- 50075381", "1");
        jobTitles.put("Compensation & Benefits Analyst- 50075381 with verification", "1");
        jobTitles.put("Business development and M&A manager", "1");
        jobTitles.put("Business development and M&A manager", "1");
        jobTitles.put("Systems technician", "1");
        jobTitles.put("Systems technician", "1");
        jobTitles.put("Compensation Benefits Manager- 50075837", "1");
        jobTitles.put("Compensation Benefits Manager- 50075837 with verification", "1");
        jobTitles.put("Recruitment Coordinator", "1");
        jobTitles.put("Recruitment Coordinator", "1");
        jobTitles.put("Senior C++ Engineer", "1");
        jobTitles.put("Senior C++ Engineer", "1");
        jobTitles.put("Senior C/C++ Engineer", "1");
        jobTitles.put("Senior C/C++ Engineer with verification", "1");
        jobTitles.put("Embedded Software Team Lead", "1");
        jobTitles.put("Embedded Software Team Lead", "1");
        jobTitles.put("Senior Commercial investments Lawyer - 50059272", "1");
        jobTitles.put("Senior Commercial investments Lawyer - 50059272 with verification", "1");
        jobTitles.put("Backend Team Lead", "1");
        jobTitles.put("Backend Team Lead with verification", "1");
        jobTitles.put("Field Engineer Team leader JB-3520", "1");
        jobTitles.put("Field Engineer Team leader JB-3520", "1");
        jobTitles.put("Senior Data Engineer", "1");
        jobTitles.put("Senior Data Engineer", "1");
        jobTitles.put("Salesforce Administrator", "1");
        jobTitles.put("Salesforce Administrator with verification", "1");
        jobTitles.put("Senior Product Manager (Prisma Cloud Data Security)", "1");
        jobTitles.put("Senior Product Manager (Prisma Cloud Data Security) with verification", "1");
        jobTitles.put("Backend Team Leader", "1");
        jobTitles.put("Backend Team Leader", "1");
        jobTitles.put("AI Hardware Sr. Pre/Post Si Validation Engineer", "1");
        jobTitles.put("AI Hardware Sr. Pre/Post Si Validation Engineer with verification", "1");
        jobTitles.put("IT Support Team Leader", "1");
        jobTitles.put("IT Support Team Leader with verification", "1");
        jobTitles.put("Engineering Team Leader", "1");
        jobTitles.put("Engineering Team Leader with verification", "1");
        jobTitles.put("Senior DevOps Engineer", "1");
        jobTitles.put("Senior DevOps Engineer", "1");
        jobTitles.put("Experienced Bookkeeper", "1");
        jobTitles.put("Experienced Bookkeeper with verification", "1");
        jobTitles.put("Payments Specialist", "1");
        jobTitles.put("Payments Specialist", "1");
        jobTitles.put("Operation Engineer", "1");
        jobTitles.put("Operation Engineer with verification", "1");
        jobTitles.put("Sales Engineer", "1");
        jobTitles.put("Sales Engineer", "1");
        jobTitles.put("Manager, Engineering - Cloud Security", "1");
        jobTitles.put("Manager, Engineering - Cloud Security with verification", "1");
        jobTitles.put("Flooring Installer", "1");
        jobTitles.put("Flooring Installer", "1");
        jobTitles.put("Dedicated Carpet Installer", "1");
        jobTitles.put("Dedicated Carpet Installer", "1");
        jobTitles.put("טכנאי.ת מערכות צי\"ד", "1");
        jobTitles.put("טכנאי.ת מערכות צי\"ד with verification", "1");
        jobTitles.put("Satellite Communications Technician", "1");
        jobTitles.put("Satellite Communications Technician", "1");
        jobTitles.put("Payroll Specialist", "1");
        jobTitles.put("Payroll Specialist with verification", "1");
        jobTitles.put("NPI Engineer", "1");
        jobTitles.put("NPI Engineer with verification", "1");
        jobTitles.put("Research Development Team Lead", "1");
        jobTitles.put("Research Development Team Lead with verification", "1");
        jobTitles.put("Application Engineer", "1");
        jobTitles.put("Application Engineer", "1");
        jobTitles.put("HR Business Partner", "1");
        jobTitles.put("HR Business Partner with verification", "1");
        jobTitles.put("DevOps team leader", "1");
        jobTitles.put("DevOps team leader", "1");
        jobTitles.put("VMWARE System Specialist", "1");
        jobTitles.put("VMWARE System Specialist with verification", "1");
        jobTitles.put("Head Of AI Guild", "1");
        jobTitles.put("Head Of AI Guild with verification", "1");
        jobTitles.put("Director of Global Talent Acquisition", "1");
        jobTitles.put("Director of Global Talent Acquisition with verification", "1");
        jobTitles.put("Cyber Security Engineer", "1");
        jobTitles.put("Cyber Security Engineer with verification", "1");
        jobTitles.put("Electrician I", "1");
        jobTitles.put("Electrician I with verification", "1");
        jobTitles.put("CD Integration and Start-Up Engineer", "1");
        jobTitles.put("CD Integration and Start-Up Engineer with verification", "1");
        jobTitles.put("Senior Backend Developer, Core Group", "1");
        jobTitles.put("Senior Backend Developer, Core Group with verification", "1");
        jobTitles.put("Medical Scientific Liaison (Contract Role)", "1");
        jobTitles.put("Medical Scientific Liaison (Contract Role) with verification", "1");
        jobTitles.put("Software Engineer III, Google Research", "1");
        jobTitles.put("Software Engineer III, Google Research with verification", "1");
        jobTitles.put("Medical Representative", "1");
        jobTitles.put("Medical Representative with verification", "1");
        jobTitles.put("מהנדס/ ת ולידיציה", "1");
        jobTitles.put("מהנדס/ ת ולידיציה", "1");
        jobTitles.put("Backend Tech-Lead", "1");
        jobTitles.put("Backend Tech-Lead", "1");
        jobTitles.put("Content Team Lead", "1");
        jobTitles.put("Content Team Lead", "1");
        jobTitles.put("Product Engineer", "1");
        jobTitles.put("Product Engineer with verification", "1");
        jobTitles.put("Senior Full Stack Developer", "1");
        jobTitles.put("Senior Full Stack Developer", "1");
        jobTitles.put("Network Administrator", "1");
        jobTitles.put("Network Administrator", "1");
        jobTitles.put("Controller", "1");
        jobTitles.put("Controller with verification", "1");
        jobTitles.put("Electrician I", "1");
        jobTitles.put("Electrician I with verification", "1");
        jobTitles.put("Junior Email Marketing Specialist – 50% Position", "1");
        jobTitles.put("Junior Email Marketing Specialist – 50% Position", "1");
        jobTitles.put("Backend Tech Lead", "1");
        jobTitles.put("Backend Tech Lead with verification", "1");
        jobTitles.put("Penetration Tester", "1");
        jobTitles.put("Penetration Tester with verification", "1");
        jobTitles.put("Senior Data Engineer", "1");
        jobTitles.put("Senior Data Engineer with verification", "1");
        jobTitles.put("ERP Financial implementer", "1");
        jobTitles.put("ERP Financial implementer with verification", "1");
        jobTitles.put("Indirect Buyer", "1");
        jobTitles.put("Indirect Buyer with verification", "1");
        jobTitles.put("Security Expert", "1");
        jobTitles.put("Security Expert with verification", "1");
        jobTitles.put("Performance Marketing Specialist (TikTok)", "1");
        jobTitles.put("Performance Marketing Specialist (TikTok) with verification", "1");
        jobTitles.put("Senior Data Scientist", "1");
        jobTitles.put("Senior Data Scientist with verification", "1");
        jobTitles.put("Data Engineer", "1");
        jobTitles.put("Data Engineer with verification", "1");
        jobTitles.put("Research Scientist - Metrology Advanced Application Group", "1");
        jobTitles.put("Research Scientist - Metrology Advanced Application Group with verification", "1");
        jobTitles.put("Information Technology System Specialist", "1");
        jobTitles.put("Information Technology System Specialist with verification", "1");
        jobTitles.put("מנהל.ת פרויקטים בייצור", "1");
        jobTitles.put("מנהל.ת פרויקטים בייצור with verification", "1");
        jobTitles.put("Senior Java Software Engineer", "1");
        jobTitles.put("Senior Java Software Engineer with verification", "1");
        jobTitles.put("Senior Java Developer", "1");
        jobTitles.put("Senior Java Developer with verification", "1");
        jobTitles.put("Technical Writer", "1");
        jobTitles.put("Technical Writer with verification", "1");
        jobTitles.put("Data Engineer", "1");
        jobTitles.put("Data Engineer with verification", "1");
        jobTitles.put("Specialist Merchandise eCommerce & Halo- Maternity Leave", "1");
        jobTitles.put("Specialist Merchandise eCommerce & Halo- Maternity Leave with verification", "1");
        jobTitles.put("Customer Training Coordinator (Student) IL", "1");
        jobTitles.put("Customer Training Coordinator (Student) IL with verification", "1");
        jobTitles.put("Software Engineer - Cloud Security", "1");
        jobTitles.put("Software Engineer - Cloud Security with verification", "1");
        jobTitles.put("Freelance recruiter for a placement company - work from home", "1");
        jobTitles.put("Freelance recruiter for a placement company - work from home with verification", "1");
        jobTitles.put("Network Engineer", "1");
        jobTitles.put("Network Engineer with verification", "1");
        jobTitles.put("Digital Marketing Specialist", "1");
        jobTitles.put("Digital Marketing Specialist with verification", "1");
        jobTitles.put("Business Development Manager", "1");
        jobTitles.put("Business Development Manager with verification", "1");
        jobTitles.put("Technical Support Engineer", "1");
        jobTitles.put("Technical Support Engineer with verification", "1");
        jobTitles.put("Database Administrator", "1");
        jobTitles.put("Database Administrator with verification", "1");
        jobTitles.put("Senior Data Analyst", "1");
        jobTitles.put("Senior Data Analyst with verification", "1");
        jobTitles.put("Salesforce Developer", "1");
        jobTitles.put("Salesforce Developer with verification", "1");
        jobTitles.put("Technical Account Manager", "1");
        jobTitles.put("Technical Account Manager with verification", "1");
        jobTitles.put("Software Engineer - Cloud Security", "1");
        jobTitles.put("Software Engineer - Cloud Security with verification", "1");

        String url = "https://www.linkedin.com/jobs/search/?alertAction=viewjobs&currentJobId=3954748434&distance=50&f_TPR=r604800&geoId=102981967&keywords=full%20stack%20engineer&origin=JOB_SEARCH_PAGE_JOB_FILTER&sortBy=R";
        for (String key : jobTitles.keySet()) {
            jobTitles.put(key, url);
        }

        return jobTitles;
    }
}
